# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\"%\n\rTargetRequest\x12\t\n\x01x\x18\x01 \x01(\t\x12\t\n\x01y\x18\x02 \x01(\t\"0\n\x0eTargetResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x62oard\x18\x02 \x01(\t27\n\x06Target\x12-\n\x08SendBomb\x12\x0e.TargetRequest\x1a\x0f.TargetResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TARGETREQUEST._serialized_start=18
  _TARGETREQUEST._serialized_end=55
  _TARGETRESPONSE._serialized_start=57
  _TARGETRESPONSE._serialized_end=105
  _TARGET._serialized_start=107
  _TARGET._serialized_end=162
# @@protoc_insertion_point(module_scope)
