# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protocol_pb2 as protocol__pb2


class TargetStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendBomb = channel.unary_unary(
                '/Target/SendBomb',
                request_serializer=protocol__pb2.TargetRequest.SerializeToString,
                response_deserializer=protocol__pb2.TargetResponse.FromString,
                )


class TargetServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendBomb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TargetServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendBomb': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBomb,
                    request_deserializer=protocol__pb2.TargetRequest.FromString,
                    response_serializer=protocol__pb2.TargetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Target', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Target(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendBomb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Target/SendBomb',
            protocol__pb2.TargetRequest.SerializeToString,
            protocol__pb2.TargetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
